apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: guestbook-ui-rollouts
spec:
  replicas: 5
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui-rollouts
  template:
    metadata:
      labels:
        app: guestbook-ui-rollouts
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui-rollouts
        ports:
        - containerPort: 80
